# -*- coding: utf-8 -*-
"""Langflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPojPsh7LEjxy2wuxRgQReD2jvCmt6os

Langflow Logic
"""

!pip install transformers gradio --quiet

from transformers import pipeline
import gradio as gr

# Load Question Answering pipeline
qa_pipeline = pipeline(
    "question-answering",
    model="distilbert-base-cased-distilled-squad"
)

# Context (knowledge base)
context = """
A database is an organized collection of data that is stored and accessed electronically.
DBMS stands for Database Management System and is used to manage databases.
SQL stands for Structured Query Language and is used to interact with databases.
A primary key uniquely identifies each record in a table.
A foreign key links one table to another table.
"""

def answer_question(question):
    result = qa_pipeline(
        question=question,
        context=context
    )
    return result["answer"]

gr.Interface(
    fn=answer_question,
    inputs=gr.Textbox(label="Enter your question"),
    outputs=gr.Textbox(label="Answer"),
    title="Transformers-based Q&A (LangFlow Logic)",
    description="Basic lab-level Question Answering using Hugging Face Transformers"
).launch()

from transformers import pipeline

# LLM component
llm = pipeline("text2text-generation", model="google/flan-t5-small")

# Prompt component
def prompt_template(user_input):
    return f"You are a helpful student assistant.\nQuestion: {user_input}"

# Langflow logical executor
def run_langflow(user_input):
    prompt = prompt_template(user_input)
    response = llm(prompt, max_length=150)
    return response[0]["generated_text"]

# Test
print(run_langflow("Explain normalization in DBMS"))