# -*- coding: utf-8 -*-
"""Sentimental_Analysis(Hugging face).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kA_5yDIvJ-o64roiA8AzBXXlF4Bc1oOD

Sentimental_Analysis using Hugging face
"""

# Step 1: Install the necessary libraries
!pip install -q transformers gradio

# Step 2: Import libraries
from transformers import pipeline
import gradio as gr

# Step 3: Load the sentiment analysis pipeline
# This downloads a pre-trained model automatically
classifier = pipeline("sentiment-analysis")

# Step 4: Define a simple function for the app
def analyze_text(text):
    result = classifier(text)[0]
    return f"Label: {result['label']}, Score: {round(result['score'], 4)}"

# Step 5: Create the web interface
demo = gr.Interface(
    fn=analyze_text,
    inputs="text",
    outputs="text",
    title="My First AI",
description="Type a sentence below to see if it's Positive or Negative!"

)
demo.launch(share=True)